[project]
name = 'vaxo'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.ft-trait]
path = 'contracts/ft-trait.clar'
depends_on = []
clarity_version = 2
epoch = 2.1

[contracts.vaxo]
path = 'contracts/vaxo.clar'
depends_on = ["ft-trait"]
clarity_version = 2
epoch = 2.1

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
